<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit4e37da12cfc5a1ceb03cd0adc1278457
{
    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'Caya\\StudentManagement\\' => 23,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Caya\\StudentManagement\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit4e37da12cfc5a1ceb03cd0adc1278457::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit4e37da12cfc5a1ceb03cd0adc1278457::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit4e37da12cfc5a1ceb03cd0adc1278457::$classMap;

        }, null, ClassLoader::class);
    }
}
